### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#103]
I took care of this last year and created the design. Will post at future date.

Designs located here https://www.dropbox.com/sh/6y5t57394im98lu/AACJGMcbu3LB1eo8kuSdCrtra?dl=0

**Comment by ultimike** [comment]
From last year's retro:

> Tore too easily
> Names too small
> Sticker name tags
> Write our own names on badges - not pre-printed.
> Some folks want only their first name. Or only their d.o. name, or their first and last name, etc...
> Nametag headbands.
> Helium balloon nametags
> Temporary tattoo nametags

**Comment by carolineachee** [comment]
You can have a field on the registration form for everyone to put what they want printed on the name tag.

**Comment by Ky1e** [comment]
@carolineachee that's a good idea. I wonder if a printer would have an issue with it, using different templates.

**Comment by Ky1e** [comment]
![lanyard_front](https://user-images.githubusercontent.com/9222546/31560495-7fa8010c-b022-11e7-8a23-7e12483cd295.png)
![lanyard_name](https://user-images.githubusercontent.com/9222546/31560499-8120c30c-b022-11e7-90ef-e28a32432b27.png)
![lanyard_back](https://user-images.githubusercontent.com/9222546/31560533-afd2229a-b022-11e7-9c15-4a87047cbf77.png)

**Comment by Ky1e** [comment]
Those are 5x7
