### ISSUE TITLE
Order Tshirts

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#106]
Natalie took care of this last year, anyone got contact info? 

Design: #105

**Comment by roberts365** [comment]
Assign it to me.

So we are looking at Gold shirts this year?
Natalie

**Comment by Ky1e** [comment]
Hey Natalie, thanks for volunteering! I sent you an invite to the group so I can assign it to you. Thanks!

Kyle

**Comment by Ky1e** [comment]
Thanks!

**Comment by ultimike** [comment]
@roberts365 Do you need anything from me to get going on this issue?

-mike

**Comment by roberts365** [comment]
@ultimike I will need the vector file for the design and date you want the shirts delivered.

**Comment by ultimike** [comment]
@Ky1e Can you get @roberts365 what she needs?

thanks,  
-mike

**Comment by Ky1e** [comment]
All the files should be here, https://www.dropbox.com/sh/m0zbakjsz54ip43/AAB034RgjV7nhVT6W3r_rRj2a?dl=0

It's the same design for the bags, with the transparent background to save on a color for shirts.

**Comment by ultimike** [comment]
@roberts365 Are we good to go here?

**Comment by roberts365** [comment]
So no gold?  Okay.  Any issues with the t-shirts being light Gray?

**Comment by ultimike** [comment]
Any color works for me as long as they look cool.

-mike

**Comment by carolineachee** [comment]
I like the idea of gray...

**Comment by roberts365** [comment]
Here is the rundown of the t-shirts so far with 143 people.

We have two options be gender.
Mens Ultra Cotton 6oz and Mens Heavy Cotton 5.3oz
Ladies Ultra Cotton and Ladies Softsyle


Mens Ultra Cotton 6oz Open Yarn |   |  
-- | -- | --
Size | Quantity | Cost Per Shirt | Sub Total
small | 2 | $8.95 | $17.90
medium | 19 | $8.95 | $170.05
large | 35 | $8.95 | $313.25
xLarge | 25 | $8.95 | $223.75
xxLarge | 6 | $10.20 | $61.20
3xLarge | 4 | $11.45 | $45.80
4xLarge | 0 | $12.70 | $-
5xLarge | 3 | $13.95 | $41.85
| | Shirt Total | $873.80
  |   |   |  
  |   |   |  
Mens Heavy Cotton 5.3oz |   |   |  
Size | Quantity | Cost Per Shirt | Sub Total
small | 2 | $6.95 | $13.90
medium | 19 | $6.95 | $132.05
large | 35 | $6.95 | $243.25
xLarge | 25 | $6.95 | $173.75
xxLarge | 6 | $8.20 | $49.20
3xLarge | 4 | $9.45 | $37.80
4xLarge | 0 | $10.70 | $-
5xLarge | 3 | $11.95 | $35.85
| | Shirt Total | $685.80
  |   |   |  
  |   |   |  
Ladies   Ultra Cotton Companion |   |  
Size | Quantity | Cost Per Shirt | Sub Total
small | 10 | $7.95 | $79.50
medium | 17 | $7.95 | $135.15
large | 11 | $7.95 | $87.45
xLarge | 6 | $7.95 | $47.70
xxLarge | 2 | $9.20 | $18.40
3xLarge | 3 | $10.45 | $31.35
4xLarge | 0 | $11.70 | $-
5xLarge | 0 | $12.95 | $-
| | Shirt Total | $399.55
  |   |   |  
  |   |   |  
Ladies Softstyle |   |   |  
Size | Quantity | Cost Per Shirt | Sub Total
small | 10 | $9.95 | $99.50
medium | 17 | $9.95 | $169.15
large | 11 | $9.95 | $109.45
xLarge | 6 | $9.95 | $59.70
xxLarge | 2 | $11.20 | $22.40
3xLarge | 3 | $12.45 | $37.35
4xLarge | 0 | $13.70 | $-
5xLarge | 0 | $14.95 | $-
| | Shirt Total | $497.55



Mens   Ultra + Ladies Ultra |  
-- | --
Shirt Total | $1,273.35
Screen Charge | $120.00
Labor | $150.00
Total | $1,543.35
  |  
  |  
Mens Ultra + Ladies Softstyle |  
Shirt Total | $1,371.35
Screen Charge | $120.00
Labor | $150.00
Total | $1,641.35
  |  
  |  
Mens   Heavy Cotton + Ladies Ultra
Shirt Total | $1,085.35
Screen Charge | $120.00
Labor | $150.00
Total | $1,355.35
  |  
  |  
Mens   Heavy Cotton + Ladies Softstyle
Shirt Total | $1,183.35
Screen Charge | $120.00
Labor | $150.00
Total | $1,453.35

**Comment by ultimike** [comment]
@roberts365 and I spoke on Feb 5, and we're going to go with "Mens Heavy Cotton + Ladies Ultra".
