### ISSUE TITLE
Bags

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#107]
I don't think we had any left over from last year. Here's what was ordered, 200 https://www.holdenbags.com/products/little-tex-grocery-bag.

**Comment by ultimike** [comment]
Looking at this bag for this year: https://www.holdenbags.com/products/two-tone-little-storm

@mherchel @Ky1e Which image should I use? Do I need one with no background? Orange bags this year to match the logo, correct?

**Comment by ultimike** [comment]
- 250 bags with 1-color imprint: $610
- 250 bags with 2-color imprint: $786

Thoughts?

**Comment by carolineachee** [comment]
Two colors would be good.....

**Comment by ultimike** [comment]
I also received some feedback on Slack about spending the extra $$$ for 2-color bags. I'm submitting the order today.

**Comment by ultimike** [comment]
The bags have been ordered (full color, not 2-color).
