### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#109]
@ultimike you mentioned you'd send the first round of emails. I hit up Ben and Dwayne at Pantheon who both confirmed they'd be attending. I'm sure they bring sponsorship with them but it needs to be confirmed. Was waiting until we locked in FTC dates.

**Comment by ultimike** [comment]
This is my number one priority - I'll get started on this immediately. 

-mike

**Comment by ultimike** [comment]
I just sent out the sponsorship opportunities emails + PDF to 52 potential sponsors. Fingers crossed.

**Comment by ultimike** [comment]
Here's an update on sponsorships. The following **cash** sponsors have confirmed - I'll be sending out invoices to all of them in the next few days:

**Platinum**

- Achieve Agency

**Gold**

- Webenabled
- Commerce Guys

**Silver**

- Acquia
- OSTraining
- Hot Sauce
- Code Journeymen
- Palantir.net

**Bronze**

- Redfin
- Kanopi
- Lullabot

This represents $8,250.

In addition there's more than a few organizations that are still in the process of deciding. 

Finally, I'm pretty sure DrupalEasy will be sponsoring as well :)
