### ISSUE TITLE
Food on Friday

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#110]
Last year we had 85 boxed lunches from TooJays. We ended up having to get a lot more. I think the count ended up being somewhere around 110-120 before we brought in pizza.

Previous order:

Boxed lunches from TooJays:
55 "no preference"
10 vegetarian
5 vegan
70 total boxed lunches (labelled, napkins, mayo/mustard, etc...)
$10.79/each
They'll bring ice tea and lemonade to drink for $6.79/gallon (6 gallons) - includes cups and everything.
They'll bring a cooler of ice as well.
I can call them next week with final numbers.
Will deliver between 11:30-noon.
I spoke with Sarah on 2/10/17 via (561) 472-0567.
Total cost: $830.93 (I paid with my business Visa)

**Comment by ultimike** [comment]
@lscook has offered to help with this - I suggest that we give folks these options, ask them to choose one at registration:

Publix Chicken tender sub - roll or wrap
Publix Turkey sub - roll or wrap
Publix Ultimate sub - roll or wrap
Publix Veggie sub - roll or wrap
Publix Italian sub - roll or wrap
Publix Roast Beef sub - roll or wrap
Publix Ham sub - roll or wrap
Publix Tuna Salad sub - roll or wrap

All will include lettuce, tomato, and we will provide mayonnaise and mustard on the side.

We can then place the order to be ready for pickup by 11:45am. We should probably give Publix a heads-up (http://www.publix.com/locations/1440-town-park) prior to placing the order.

I will bring several cases of water.

Cool?

**Comment by lscook** [comment]
Do you think they'll have enough time to get it all ready by 11:45 am if we get the order in by 9:15? How many are we expecting? I'll give Publix a call and talk to them and get back with you.

**Comment by lscook** [comment]
Just got off the phone with Publix. They need the order 24 hours ahead of time. Bradley at Publix suggested we order a Sub Selection or a wrap variety platter for so many people. I told him between 50-70 people. Let me know what you decide.

Publix large sub selection serves 28 $60 http://www.publix.com/pd/publix-deli-sub-selections-large/RIO-PLT-104906?ch=6.10.
Publix large wrap plater serves 28 $60 http://www.publix.com/pd/publix-deli-sub-selections-large/RIO-PLT-104906?ch=6.10.
4 or 5 of these should be enough, 5/$300

We would need paper plates and napkins, serving tongs etc.

**Comment by ultimike** [comment]
@lscook This is fine with me - let's get 5 of these, I'd say 2 sub platters and 3 wrap platters, with a good selection of different kinds of fillings(?), including some that are all veggie. 

Would you mind handling placing the order, as well as getting the plates, napkins, etc prior to Friday? I'll still handle the bottled water.

Obviously, save your receipts, we'll pay you all back for everything.

**Comment by lscook** [comment]
By "all veggie" does that me no cheese?

**Comment by ultimike** [comment]
I think so, yes.

-mike

**Comment by lscook** [comment]
Platters are ordered. Details below:
Publix at TOWN PARK (#1440) 
12231 EAST COLONIAL DRIVE 
ORLANDO,FL-32826 
407-482-1245 
Pickup Date / Time: Friday, 02/16/18 at 11:00 AM Eastern
Pickup Name: Linda Cook
Pickup Number: 1440-9447

Yum yum.

**Comment by ultimike** [comment]
Thank you!

-mike

**Comment by lscook** [comment]
You're welcome! BYOC--bring your own chips ;)

**Comment by lscook** [comment]
3 Biscuit and mustard platters, 1 french fried pertater platter, and a potted meat platter easy on the L & P. Should be something for everybody.
