### ISSUE TITLE
Friday (free) Trainings

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#111]
Need to hit up Steve from OSTraining to see if he's available for beginner track.

**Comment by ultimike** [comment]
I'll email Steve now. 

I'll also volunteer to do a "Drupal 8 Configuration System Basics" workshop (same as I'm doing at BADCamp - https://2017.badcamp.net/training/drupal-8-configuration-system-basics).  

-mike

**Comment by stevejburge** [comment]
Happy to help, but I only if you bring the alligators again this year.

**Comment by Ky1e** [comment]
Hah! We've talked about bringing Skywalker's dad for some gator rides. FTC mentioned something about insurances and liabilities? I'm not sure but I think it'll be fine...

Thanks @stevejburge!

**Comment by mherchel** [comment]
I talked to John Tucker, and he's willing to do ReactJS training again! He has it in his calendar.

**Comment by ultimike** [comment]
Kelly Albrecht from Last Call Media (also a sponsor) is interested in giving a "Agile with Drupal" workshop - I'm working on getting all the details.

**Comment by ultimike** [comment]
List of trainings to be posted on the web site (@mherchel pay attention!):

*  Kelly - Agile  
*  John - React  
*  Wes - CSS  
*  Steve - beginner  
*  Mike - config system

I will get all the descriptions and post on the site, after that, I'll update the registration form as well as email previously registered folks about these.

-mike

**Comment by ultimike** [comment]
All training descriptions on are the site except for Steve Burge's - I just emailed him requesting a title and description.

Once I have Steve's, I'll do the following:

1.  Add it to the /training page.  
2.  Add the options to EventBrite.
3.  Email all current registrations asking them if they'd like to signup for a training - I'll have to handle these manually :(
4.  I'll coordinate with @gscampbell64 for some social media posts.  
5.  I'll coordinate with @mherchel for a newsletter blurb.  

Missing anything?

**Comment by ultimike** [comment]
I've received Steve's information, and have taken care of steps 1 and 2 above. In a few days, I'll take care of the remaining steps.

-mike

**Comment by ultimike** [comment]
Current registration counts for each class:

- CSS: 9
- Config management: 7
- React: 6
- Intro to D8: 4
- Agile: 3 
- Backdrop: 0

**Comment by ultimike** [comment]
Updated counts.

- CSS: 9
- Config management: 9
- React: 11
- Intro to D8: 6
- Agile: 3
- Backdrop: 0
- Accessibility: 0

**Comment by ultimike** [comment]
Updated counts.

- CSS: 10
- Config management: 11
- React: 12
- Intro to D8: 7
- Agile: 5
- Backdrop: 0
- Accessibility: 1

**Comment by ultimike** [comment]
New counts.

- CSS: 10
- Config management: 11
- React: 12
- Intro to D8: 8
- Agile: 5
- Backdrop: 0
- Accessibility: 1

**Comment by ultimike** [comment]
Updated counts.

- CSS: 11
- Config management: 15
- React: 17
- Intro to D8: 11
- Agile: 6
- Backdrop: 0
- Accessibility: 1

**Comment by ultimike** [comment]
...and another update:

Updated counts.

- CSS: 11
- Config management: 15
- React: 18
- Intro to D8: 11
- Agile: 6
- Backdrop: 0
- Accessibility: 1

**Comment by ultimike** [comment]
Moar numbers!

- CSS: 11
- Config management: 15
- React: 21 (sold out)
- Intro to D8: 15
- Agile: 7
- Backdrop: 0
- Accessibility: 1

**Comment by ultimike** [comment]
T-2 days!

- CSS: 13
- Config management: 16
- React: 23 (sold out)
- Intro to D8: 16
- Agile: 8
- Backdrop: 0
- Accessibility: 2

**Comment by ultimike** [comment]
Here's the final update on training registrations:

- CSS: 14
- Config management: 17
- React: 22 (sold out)
- Intro to D8: 16
- Agile: 9
- Backdrop: 0
- Accessibility: 2
