### ISSUE TITLE
Sunday Food

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#113]
We need someone to help manage the food for Sunday. Tasks include:

Buying drinks, donuts, and bagels and having them at the venue first thing (you will obviously be reimbursed).
Managing leftovers from Saturday.
Being the first one there on Sunday to open the building and get things set up.

This task can be split up between multiple volunteers.

**Comment by ultimike** [comment]
Absolutely - I need to step back from taking care of this as well as being the first one there on Sunday to open the building and get things set up...

**Comment by Bowevil** [comment]
If I am locally I can take this on.

**Comment by ultimike** [comment]
@Bowevil Fantastic! Let's discuss soon.

**Comment by Bowevil** [comment]
I will be moving up to VA for a fantastic Drupal opportunity starting on the Feb. 22nd. I am not sure if I can still help on this.

**Comment by capysara** [comment]
Can I just reply to this email?

I can do this.

**Comment by Bowevil** [comment]
That sounds good to me. Thanks @capysara

**Comment by ultimike** [comment]
Thanks, @capysara. There's nothing for us to do yet regarding this, it's mostly day-of stuff.

thanks,  
-mike
