### ISSUE TITLE
Swag to purchase

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#114]
Cielooooooo... We're getting started early to make sure we have plenty of time for swag ordering. We should have the mold for chocolates left over from last year. We did a design yesterday but it needs some tweaks. Should be done soon.

@ultimike did we have anything left over?

**Comment by ultimike** [comment]
I don't believe so. Caroline can probably confirm.

This is probably part of a bigger discussion - if we want to adopt "registration levels" - something along the lines of (just spitballing here):

*  Pay $15 - no t-shirt or anything  
*  Pay $30 - t-shirt  
*  Pay $50 - polo shirt  
*  Pay $75 - hoodie (Cielo has been lobbying for this for years)  
*  Pay $100 - get all three

**Comment by carolineachee** [comment]
I do not have any left overs... 

If the plan is to have different levels of registration we will need to make sure that the data is transferred from Eventbright to the Drupal site. As well as that there is a deadline for registration to get the additional items.

**Comment by ultimike** [comment]
Additional info for potential volunteers to help with this task:

- This doesn’t include t-shirts.
- It includes the camp bags (which is easy, I have all the info).
- @mherchel will order any stickers we need.
- So, all that’s left is any fun stuff we want to include. We’re toying with the idea of individual sponsor levels getting extra swag. So, if you pay $50, you get a bonus swag thing, $100, some other bonus swag thing.
-  In the past, we’ve had special swag for featured speakers and presenters, although @jcl324 and @bladwin might be handling that this year.

So, there’s some research into finding suitable vendors and prices, the actual ordering, then the organizing of who gets what. 

Easy peasy.

**Comment by C13L0** [comment]
These are my recommendations

**For presenters**
50 @ 7.99  ($479.50)
https://www.discountmugs.com/product/pllg9354-customized-venezia-quilted-memo-pad-sets/

**For everyone**
375 at $1.16 each ($435.00)
Similar to Cielo’s little book ;)
https://www.discountmugs.com/product/sm3482-custom-printed-recycled-pocket-notebooks/

300 at $1.46 each ($438.00) Water bottle neoprene insulator
https://www.discountmugs.com/product/kznp002-neoprene-water-bottle-drawstring-insulators/

300 at $2.55 each ($765.00)
Tea/Cappuccino-Microwave and Dishwasher safe
https://www.discountmugs.com/product/sph1017-8-oz.-vitrified-restaurant-grade-mugs/

**Comment by ultimike** [comment]
@C13L0 During a call today with @mherchel and @Ky1e, none of the three of us are super-crazy about the presenter swag - are there any other options? How about branded flip-flops - see http://www.customlogoflipflops.com/ - we think these would be a fun and desirable gift, especially if they're good quality.

We're cool with the rest of the swag.

Thoughts?

**Comment by C13L0** [comment]
I think that is a great idea but how are we going to get the sizes needed?

**Comment by Ky1e** [comment]
Could be registration form or just order generic sizes.

**Comment by JCL324** [comment]
Are flip flops really that popular with non-Floridians which are a large part of our speaker base? And they don't last very long either. I would think we'd want something a bit more permanent that would would be useful more times of the year.

**Comment by Ky1e** [comment]
Could hang the flippy floppys on the wall.

**Comment by ultimike** [comment]
@JCL324 How about indoor flip-flops?

@C13L0 In looking at the numbers, let's try to keep the total swag budget to under $2k.

**Comment by JCL324** [comment]
How about socks? Everyone uses them and sizing is much easier. Quick Google showed this: http://www.awesome-sports.com/Custom-Logo-Sports-Knee-High-Socks.html

**Comment by C13L0** [comment]
Everyone...as in guys

Those are not the type of socks that women wear

**Comment by C13L0** [comment]
For women: 
http://www.awesome-sports.com/Ankle-Socks-Quarter-Socks-For-Women-And-Men

**Comment by C13L0** [comment]
If you guys want to go with socks, I would recommend the "cool" no show or low cut here:
http://www.customlogoflipflops.com/custom-socks

just to point out this is much more expensive than my original suggestion

**Comment by Ky1e** [comment]
I actually prefer thigh high if we could throw this in the ring for consideration. Something like this, 

http://www.partycity.com/product/adult+christmas+thigh+high+stockings+with+bows.do

**Comment by C13L0** [comment]
Text changed to outlines for printing purposes. Uploading print ready ai (zipped) and pdf files. 
[drupal-18-print-ready.pdf](https://github.com/florida-drupalcamp/fldc-issues/files/1632599/drupal-18-print-ready.pdf)
[drupal-18-print-ready.ai.zip](https://github.com/florida-drupalcamp/fldc-issues/files/1632601/drupal-18-print-ready.ai.zip)

**Comment by C13L0** [comment]
AI file without background. @roberts365 will need this for t-shirts

[drupal-18-print-ready-nobg.pdf](https://github.com/florida-drupalcamp/fldc-issues/files/1632687/drupal-18-print-ready-nobg.pdf)
[drupal-18-print-ready-nobg.ai.zip](https://github.com/florida-drupalcamp/fldc-issues/files/1632690/drupal-18-print-ready-nobg.ai.zip)

**Comment by C13L0** [comment]
@Ky1e 

Could we get the logo's with less colors? We can't afford the full color.

- [ ] One color logo
- [ ] Three color logo

**Comment by C13L0** [comment]
@ultimike I'm not sure who created this years logo but I really need it in a one color and three color

**Comment by ultimike** [comment]
You had it correct the first time - it is @Ky1e. I'll ping him on Slack as well.

**Comment by Ky1e** [comment]
Sent all needed files on Slack and saved them all in Dropbox.

**Comment by ultimike** [comment]
Cielo,

Safe to assume all the swag is ordered?

thanks,  
-mike
