### ISSUE TITLE
Indoor signage

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#115]
I think we're using the signage from last year. @ultimike Do we need anything here?

**Comment by ultimike** [comment]
From last year's retro:

> Add two additional directional signs at the intersection of the two classroom wings that list which rooms are located in that particular wing.
> FLDC18: Steven can start creating signage as soon as new logo is posted and approved.

@mherchel also mentioned that we have several hundred dollars in signage from previous years with the old logo - I'm not so bothered by re-using it.

From what I remember, Cielo is pretty good at identifying what we need for signage...

**Comment by StevenGFX** [comment]
I can take over these duties

**Comment by Ky1e** [comment]
Awesome-sauce! I've got all the creative files so let me know what you need.

**Comment by ultimike** [comment]
@StevenGFX Please confirm that you're still interested in helping out with this.

thanks,  
-mike

**Comment by StevenGFX** [comment]
@ultimike Iam!
