### ISSUE TITLE
Code Sprint

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#116]
Notes from last year:
xjm suggested that we do a major issue triage sprint at FLDC (see http://xjmdrupal.org/blog/drupal-8-major-triage-new-orleans and https://www.drupal.org/node/2474049).

We're thinking we could do this on Sunday.

In order to make this happen, we need some sprint leads.

**Comment by ultimike** [comment]
From last year's retro:

> Having some sessions on Sunday morning worked well, as folks came for the sessions and stayed for the sprint.
> Having a few folks there from the start was helpful to beta test the sprint instructions.
> Better pre-sprint description (in email newsletter and/or schedule and/or opening/closing session)
> Excel doc and flow chart were very helpful
