### ISSUE TITLE
Sponsor Happiness - day(s) of event

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#117]
During the event, we're going to need a couple of volunteers to visit each of the sponsors at their tables (or where ever they might be) to ensure they have everything they need and (more importantly) let them know how much we appreciated their involvement.

Things we can offer include:

1.  Make introductions with attendees.  
2.  Escort sponsors to the front of the lunch line (this is a new, unadvertised perk we're giving sponsors).  
3.  Other ideas?

**Comment by Ky1e** [comment]
I did this along with @ultimike and it still didn't seem like enough. Need some assistance party people.

**Comment by lscook** [comment]
I did this one year and we also used tickets to promote the sponsors. Sponsors gave out tickets to attendees who stopped by their tables. The tickets were used for prize drawings at the final session. I gave some tickets to the presenters too so they could give them out. If I saw a session room with few attendees I stood outside the door and gave tickets out when people walked in and sat down to boost attendance. Volunteers also had tickets to give out. I think we put some in the swag bags as well. I received tons of positive feedback from sponsors who were kept busy all day talking with attendees.

**Comment by Ky1e** [comment]
Now THATS a kickass idea @lscook

**Comment by ultimike** [comment]
Yep, great idea - sounds like we need a few "day of" volunteers to help out with this.

**Comment by lscook** [comment]
Aw...shucks. Thanks.

**Comment by ultimike** [comment]
The following sponsors have requested tables:

1. Webenabled/DevPanel
2. Lingotek
3. Johnson & Johnson
4. DrupalEasy
5. Drud
6. OSTraining
7. PayKings

**Comment by Ky1e** [comment]
@lscook are we going forward with the ticket idea? We can probably retain a few of the key swag items to be given out.

**Comment by ultimike** [comment]
I vote no. Keep it simple. Linda doesn't need to be doing more stuff.

**Comment by lscook** [comment]
I agree with Mike.

**Comment by Ky1e** [comment]
I agree with Kyle so it's 2 v 2, what do we do now?
