### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#118]
Caroline and Karan rule the registrations with iron fists. Nuff' said.

**Comment by ultimike** [comment]
From last year's retro:

> Bring a printer to the camp on all days.
> Do manual counts on Friday and Sunday.

**Comment by carolineachee** [comment]
Sign me up!

**Comment by Ky1e** [comment]
The real mvp!

**Comment by ultimike** [comment]
Achieve will be providing the lanyards again this year.

**Comment by carolineachee** [comment]
I will work with John about the type of clip he get for the lanyards.

**Comment by carolineachee** [comment]
Mike,

I see that the registration data is not on the website. Could I get a Eventbright dump to see how things are going or a logon for eventbright?

Thanks,
Caroline

**Comment by ultimike** [comment]
Caroline,

No problem - I'll export and send you a .csv now.

thanks,  
-mike

**Comment by carolineachee** [comment]
Mike,

Do you have a registration code for the Key speakers... I would like to start making sure that all the speakers/presenters are registered.

Thanks,
Caroline

**Comment by ultimike** [comment]
@carolineachee Please ensure that we have a different color lanyard for folks that don't want their photos taken during the event.

**Comment by ultimike** [comment]
@carolineachee I'll email the featured speakers right now and let them know to use the `fldcvolunteer` registration code.

**Comment by carolineachee** [comment]
@ultimike 

We have some red lanyards we can use.

Caroline

**Comment by carolineachee** [comment]
@ultimike!

Can I get a new Eventbright dump??

Thanks,
Caroline

**Comment by ultimike** [comment]
@carolineachee Yep - I'll email it to you now.

Also - heads-up, Achieve will be supplying lanyards again this year - they'll be drop-shipping them directly to me.

-mike

**Comment by carolineachee** [comment]
@ultimike  I just want to make sure ... presenters need to pay for camp? I have done some checking and 1/2 of the approved session presenters are not registered and there is only 12 sessions approved... Do you know when the rest of the session will be approved.

count
Men  -  91
Women -  42
Total - 133

Thanks,
Caroline

**Comment by carolineachee** [comment]
@ultimike Could you get me a list of the corporate sponsors names so that I can make sure they are marked for the sponsor ribbon... Also can I get included in the dump the individual sponsors?

Thanks,
Caroline

**Comment by ultimike** [comment]
Caroline,

Sessions have been approved - notifications will be going out today or tomorrow. If a presenter asks, we will provide them with a free registration code.

You already have access to the Sponsorships spreadsheet - I'll email you the link now.

thanks,  
-mike

**Comment by carolineachee** [comment]
Mike,

 

Thanks for the update!


Caroline
