### ISSUE TITLE
Town Crier - Social Media

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#121]
The social media wrangler will post various information on our social media account in the time leading up to the camp. In addition, after the camp, we'll need to send out posts thanking attendees, speaker, trainers, and sponsors.

Ideally, we’d like 1-2 posts per day on each of the following:

https://twitter.com/fldrupalcamp
https://www.facebook.com/groups/43405081389/
https://www.linkedin.com/groups/105073

We’ll need sponsor tweets (weighted by sponsorship level) - see https://docs.google.com/spreadsheets/d/1q4wbQKCXBwFCyr28xHj0OHzElHl1ERbG4hnhR1Cr68U/edit as well as general tweets promoting the camp.

We could have multiple people on this task.

**Comment by Ky1e** [comment]
@gscampbell64

**Comment by ultimike** [comment]
Another idea - DrupalCamp Atlanta is advertising on Yahoo - every time I hit a page on yahoo.com, I see a DCATL ad. I've reached out to one of the organizers to see what their ROI is. I'll post back here when I find out.

**Comment by Ky1e** [comment]
I've got a buffer subscription I can schedule these with. Need info so we can start this.

**Comment by gscampbell64** [comment]
I may be a little behind the 8-Ball on this but I'm on it!  Need links from @ultimike.

**Comment by ultimike** [comment]
@gscampbell64 I just shared the Google Sheet with you as well as a bunch of info about it.
