### ISSUE TITLE
Session Acceptance

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#124]
When issuing an acceptance of a session please ensure they register for the camp if they are not already registered. Some speakers tend to wait until their session is accepted to register but sometimes forget. We had an issue with this last year.

**Comment by ultimike** [comment]
Also - I'd like to propose that speakers get a free registration coupon code.

**Comment by jeppy64** [comment]
Please see [https://github.com/florida-drupalcamp/fldc-issues/issues/122](url)

**Comment by Ky1e** [comment]
I'll run a check after we publish the schedule to make sure everyone is scheduled.

**Comment by ultimike** [comment]
This task also includes things like: promoting when our session proposals are open, reviewing/selection/scheduling sessions, ensuring diversity, etc…

**Comment by ultimike** [comment]
@helenasue How is this task going? How many sessions have been accepted? Have all accepted presenters been notified? Is everything on-track?

thanks,  
-mike
