### ISSUE TITLE
Venue notes

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#126]
As in previous years, we will pay for security and custodial services. FTC will provide a key holder for us to assist us.

Contact info:
Mrs. Andrea Meda-Pollock - Director of Career Services
Email: apollock@ftccollege.edu
Phone: (407) 447-7314

Edit: Andrea left, her replacement is Maryann at the same number. 

I had a meeting with Andrea where we confirmed that we are locked in for presidents day weekend. She was extremely helpful and said she loved having us at FTC.

**Comment by Ky1e** [comment]
Handing off to @ultimike for other details.

**Comment by ultimike** [comment]
I'll email Andrea today with some additional details and to get the ball rolling...

-mike

**Comment by ultimike** [comment]
Here's the text of the email I sent:

> Andrea,
> 
> Thanks so much for your willingness to host us again in 2018! We absolutely love and appreciate everything FTC has done for us over the years and hope it will continue in the future.
> 
> First off - if there’s anything we can to do make our event more beneficial to FTC staff or students - just ask. We’re open to just about anything.
> 
> Please allow me to add some additional details to the information Kyle provided below.
> 
> Friday, February 18: We would like access for up to 6 classrooms (~80 attendees) for full-day training sessions (we will have a better idea of the exact number as we get closer). We would also like to use the student lounge to provide lunch to participants. While the trainings will go from 9-4pm, we would like to ask folks to show up as early at 8am to register and get set up. So, let’s assume 8am-5pm.
> 
> Saturday, February 19: This is our biggest day - this is a full day of sessions with somewhere around 300 attendees. We’d like access to the building from 7am-6:30pm, including setup and cleanup. Ideally, we’d like access to the same rooms we’ve used in the past: auditorium, library, 6-8 classrooms, lobby, hallways, student lounge. 
> 
> Sunday, February 20: This is similar to Saturday, but on a smaller scale. We expect somewhere between 150-200 attendees, with the same level of building access as Saturday. Figure 8am-5pm. 
> 
> General notes:
> 
> *  There was an issue this past year with the A/C being enabled on both Saturday and Sunday. We were told it was on an automated schedule and no one was available to override it. We’d like to avoid this issue again, if possible.
> *  As in previous years, we will absolutely pay for security and janitorial services on Saturday and Sunday. Please let me know what will be required and the best way for us to set it all up.  
> 
> If you have any questions at all, don’t hesitate to call or email me.
> 
> Thank you!
> -mike anello

**Comment by ultimike** [comment]
@Ky1e Will touch base with FTC to ensure all is still on-track. Find out what, if anything, we need to do for security and/or custodial stuff.
