### ISSUE TITLE
website: Featured speakers do not collapse properly at mobile width

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#132]
These should start stacking at some point 

![image](https://user-images.githubusercontent.com/1605905/33558250-64d269d4-d8d7-11e7-81e0-d95378780a03.png)

**Comment by shaal** [comment]
I'm starting working on this

**Comment by shaal** [comment]
I submitted changes in 'david' branch. (please notice it includes some config update for views and image style)
https://david-relativity-for-event-management.pantheonsite.io/

**Comment by grshane** [comment]
Fixed ready for review from FLDC group. @mherchel
