### ISSUE TITLE
Beach Towel Swag

### ISSUE THREAD

**Issue by runnergirl1** [florida-drupalcamp/fldc-issues#137]
I talked with Janellew@towelsoutlet.com regarding information in the purchasing of a large quantity of beach towels, as potential swag for the Florida Drupal Camp.  She was extremely helpful and knowledgeable.  Here is what I found out (which btw sounds VERY doable if the cost fits within the Camp's budget!)

They are located in Miami. . .being a "Florida" order, you would get it even sooner.
Their website is:  www.towelsoutlet.com   phone number:  877-998-6935
There are 4 sizes of beach towels (and numerous colors!. .including several that would fit the FL Drupal Camp logo!).  The sizes are; 28x50, 30x60, 32x64, 34x70.  
The 34x70 (with the mass qty we would be ordering) costs $11.48 each.  For one color of silk screening, it would add $2.75 to the towel cost.  Janelle said their ink does not fade and is made to last.  They also offer embroidery.
We would need to send the artwork for the Camp logo to them so their art department could estimate costs for either the silk screening or the embroidery.  
If we purchased a colored towel, then possibly we would only need 2-3 other colors to match the logo for the silk screening.
Custom orders can take up to 1 week (7-9 business days) and they also offer RUSH orders.  I told her the Camp dates and she sounded like that would be 'no problem' at all.  I'm attaching the estimate form we would need to fill out and return back to her to get exact prices.

I'm unsure of what the swag budget is (this company is also offering 5% off our order). . .but this could be an item that the attendees could use regularly and also market Drupal to the community.  Atleast the 'beach' community.  ^_^
[Silk-Screen Form.pdf](https://github.com/florida-drupalcamp/fldc-issues/files/1612600/Silk-Screen.Form.pdf)

Carla

**Comment by C13L0** [comment]
I think this is a great idea! Please follow up with @ultimike on this =)

**Comment by ultimike** [comment]
Thanks @C13L0! 

At this point, the only swag we have left to figure out and determine is for presenters and sponsors (about 75 pieces). If someone would like to take this task and run with it, let us know. We would like to keep the cost to less than $10/piece.

-mike
