### ISSUE TITLE
Swag for presenters and sponsors

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#138]
We'd like to get some special swag for presenters, workshop trainers, and sponsors, but we need a volunteer to task this task on.

The budget is roughly $10/item, with a quantity 75 pieces.

Ideas for this have been discussed:

- https://github.com/florida-drupalcamp/fldc-issues/issues/114
- https://github.com/florida-drupalcamp/fldc-issues/issues/137

But we're open to anything cool and branded with our logo.

**Comment by jordanafung** [comment]
So how about a thermos/tumbler thingy:
- http://www.drinkbranders.com/custom-travel-mugs/16-oz-stealth-mug.html - $480
- http://www.drinkbranders.com/custom-contigo/16-oz-byron-by-contigo.html - $1008

This is something that is not gender or age specific, can be used by everyone regardless of where in the world the are.

About the options:
We could also purchase the Contigo ourselves and let a local print shop add our logo's - they are $6.73 pre-tax at Amazon and Walmart. I'd much prefer the contigo tbf but they are more expensive, but the quality is really good - I have like 3 of them now :)

**Comment by ultimike** [comment]
@jordanafung Do the prices you have listed above include our branding on each item?
