### ISSUE TITLE
Figure out featured speakers

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#42]
This is a blocker for launching the website

cc @ultimike

**Comment by mherchel** [comment]
First speaker is done. No longer a blocker.

**Comment by ultimike** [comment]
Second speaker has been invited, she is definitely interested, but needs time to determine her travel schedule, will let us know by November 1.

**Comment by mherchel** [comment]
Third speaker is confirmed. @ultimike let us know when speaker #2 is confirmed.

**Comment by mherchel** [comment]
@ultimike confirmation on speaker #2 yet?

**Comment by ultimike** [comment]
I just pinged her - I'll let you know as soon as I know.

thanks,
-mike

**Comment by ultimike** [comment]
Speaker #2 is now confirmed. She asked me what topics she should speak on. 

I'm thinking we should have her present a single-length session right after the opening. Perhaps a bit of a tour-de-force of what the DA does, how it is organized, their current focus, and a summary of things they've done lately. 

It would be interesting to hear about the challenges that they've been having making the transition from supporting D8 development to promoting the "adoption journey" to D8. 

Thoughts?

thanks,  
-mike
