### ISSUE TITLE
Figure out who will be managing the FLDC financing

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#43]
Will it be the DA or CFCS?

We may need to update Eventbrite's bank account info

cc @ultimike

**Comment by ultimike** [comment]
I'll email Don and ask him to chime in on this issue. 

Knowing what is going on with the DA (belt-tightening), I'd prefer to stay with CFCS, but Don will have to let us know if that's still feasible.

-mike

**Comment by caelon** [comment]
I will check with Betty Ann, CFCS Treasurer. Last I knew, they were a bit more stable than six months ago. I think we'll be fine with CFCS but will need to just know that there's an open risk they could fold. That shouldn't affect our cash (they wouldn't be closing for financial reasons - they have plenty of cash - but rather lack of members) but we'd have to scramble for the 501c3 classification at that point.

**Comment by mherchel** [comment]
@caelon thanks. Is the only benefit of the non-profit designation that we get tax-breaks on tshirts, catering, etc?

**Comment by mherchel** [comment]
We're now officially accepting registrations. Can we confirm that we'll be using CFCS?

**Comment by mherchel** [comment]
@caelon Did you ever get a reply from the CFCS treasurer

**Comment by caelon** [comment]
Yeah, answer hasn't really changed. We can move forward with staying where we are at the moment with the knowledge that it's a group that is struggling with membership. That shouldn't affect us beyond what we can manage.

**Comment by mherchel** [comment]
Cool. Let's close this out then. We'll stay with CFCS, and go from there. Thanks Don! 

cc @ultimike
