### ISSUE TITLE
Put archived 2016 site up on 2016.fldrupal.camp

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#44]
Put archived 2016 site up on 2016.fldrupal.camp

**Comment by mherchel** [comment]
@JCL324 Are you able to throw up the archived site? If not, let me know and I can handle it (but I think you still control the DNS)

**Comment by JCL324** [comment]
Yes, it's on my to-do list.

**Comment by JCL324** [comment]
2016 archive is up. Also created 2017.fldrupal.camp that redirects. Closing.
