### ISSUE TITLE
Update EventBrite integration

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#46]
Alex,

In talking with Jay and Mike H, it sounds like we need to update the EventBrite to work with the new EventBrite API.

We're looking to launch the FLDC D7 site in the very near future, so if updating the D7 module is an easy task, let's go ahead and do that first. Jay Epstein is working on a D8 version of the site, that we're planning on switching over to as soon as its ready.

If updating the D7 module is going to be anything more than a straight-forward task, let's go ahead and port it to D8 (and skip D7). 

In addition, if you're too busy, Jay is suggesting that you might be able to hand this off to Kyle - he can probably handle this with a little guidance. 

Finally, if it will help with the timeline, FLDC can sponsor some of the development, provided the module is contributed to the community and available on d.o. (it may be already, I'm not sure).

Thoughts?

thanks,  
-mike

**Comment by mherchel** [comment]
Closed in favor of https://github.com/florida-drupalcamp/fldc-d7/issues/1
