### ISSUE TITLE
What's the overall schedule for the camp?

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#48]
We talked about moving things around after last year.

Friday:
* Trainings
* Code Sprint

Saturday
* Sessions
* Two Featured Speakers

Sunday
* Sessions
* One Featured Speaker
* Code Sprint

Is this right??

@ultimike

**Comment by mherchel** [comment]
Where is the OS Training stuff going to fit in?

**Comment by ultimike** [comment]
Yes, what you have is what we talked about - just some details are missing...

Friday:
* Trainings (including the free beginner track, pending OSTraining agreeing)
* Code Sprint

Saturday
* Sessions
* Two Featured Speakers

Sunday
* Sessions (half-day)
* One Featured Speaker
* Code Sprint

**Comment by mherchel** [comment]
I like putting OS Training in on Friday, then the users can participate at the camp on Saturday. But, do you think we'll still have a decent turnout on Friday? I think we can.

**Comment by ultimike** [comment]
I think it will be a smaller turnout, but it's a necessary change. I think
the benefit of having them participate in the rest of the camp over the
weekend is huge.

-mike

**Comment by mherchel** [comment]
@ultimike Just to confirm, we've verified that Friday is okay with FTC?

**Comment by ultimike** [comment]
Yep.

-mike

**Comment by mherchel** [comment]
I also want to do lightning talks. Maybe the last hour of Saturday, we can budget some time to do impromptu lightning talks. I have several that I can give. I also talked to Connerton, who has several.

**Comment by mherchel** [comment]
FYI, I created an overall schedule page. https://www.fldrupal.camp/overall-schedule

Closing this issue out.
