### ISSUE TITLE
Reach out to OS Training

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#49]
Check w Steve from OS Training to see if they're in.

**Comment by mherchel** [comment]
Any update on if they're down for doing this on Friday?

**Comment by ultimike** [comment]
I just emailed Steve Burge to confirm.

thanks,
-mike

**Comment by ultimike** [comment]
Steve is confirmed.

**Comment by ultimike** [comment]
Re-opening issue. Steve may not be able to make the camp after all - he'll let me know for sure in a few days.

**Comment by mherchel** [comment]
Any update on Steve for Friday?

**Comment by ultimike** [comment]
I just pinged Steve to confirm - I'll let you know as soon as I know.

I also sent emails to Ray from FFW and Suzanne from Evolving Web asking if
they were interested in doing trainings on Friday.

In addition, I'm probably going to do one as well.

-mike

**Comment by ultimike** [comment]
Steve can't do it - closing this issue in lieu of https://github.com/florida-drupalcamp/fldc-issues/issues/60

-mike
