### ISSUE TITLE
Invitation letter for foreign visitors

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#51]
We've already had a request for an "invitation letter" for a visitor interesting in attending our camp, but in need of a visa to do so. In situations like these, sometimes the visitor needs an official invitation letter from the event organizers in order to secure the visa.

I've contact the Drupal Association about this for their advice, and they've provided a letter which I (slightly) customized for our event. It can be found here: https://docs.google.com/document/d/1JqINc6uRvTDhbm8qJeHg1t36x-jz63h6R2RqFjEilLU/edit

For some additional background information, here's what Amanda from the DA wrote:

> We don't put together visa letters for events that aren't DrupalCon but I've attached a sample letter of invitation that I use for DrupalCon New Orleans. You can use it as a sample and modify the language for the Florida DrupalCamp. Most consulates require an official invitation from the event organizers to confirm that the visa applicant is actually registered for the conference. It is important to have the applicant's full name (as it appears on their passport), date of birth, passport number, expiration date and country that issued the passport on the letter. We use this webform (https://events.drupal.org/dublin2016/request-visa-letter) to collect the passport information from attendees who need a visa and then issue the letters manually as PDFs. Most consulates accept PDFs, but some require a printed copy that you may have to mail to the attendee.
> 
> However, while an official letter of invitation increases the chances of visa applications being granted, it does not guarantee anything. The application may still get rejected and as sad as this is, there's not much you can do about it.

-mike

**Comment by ultimike** [comment]
Mike H - I've responded to Lucía Abaca asking for some additional information.

thanks,  
-mike

**Comment by mherchel** [comment]
This guy has been emailing us:

````
Good morning, do you know something about the letter asked? 

Lucía. 

````

**Comment by ultimike** [comment]
This is all set now - I just sent the letter via email.

-mike
