### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#52]
Badges

**Comment by Ky1e** [comment]
I can handle the printing.

**Comment by mherchel** [comment]
https://www.dropbox.com/sh/g7sjp9n4x63k1tb/AABWmHJuxlSkgeFUOsw19ckWa?dl=0

**Comment by Ky1e** [comment]
What's the budget for badges?

**Comment by mherchel** [comment]
![image](https://cloud.githubusercontent.com/assets/1605905/22299111/ee3eb21e-e2f0-11e6-898e-c6c28e4590c2.png)

**Comment by ultimike** [comment]
Anything reasonable. Just let me know.

thanks,
-mike

**Comment by Ky1e** [comment]
Working up the redesign and estimate w/ printer now.

**Comment by Ky1e** [comment]
Badges w/ plastic holder and lanyard.

Quantity Description Price
300 Lanyards 1 Original (2 sides)
Preflight: Preflight
Cover Coated: 100# Blazer Digital Cover Gloss 3 x 4 (1 Original)
Front: Color
Back: Color
Promotional Products: Lanyards

Total: 1,155.00

**Comment by Ky1e** [comment]
@ultimike What's a reasonable price? :P

**Comment by ultimike** [comment]
Hrm - badge spending from previous years:

2016: $208
2015: $178
2014: $608
2013: $384

I honestly don't mind spending the money, but why is it so much more than previous years? Are they much different?

@carolineachee - do we have badge holders and/or lanyards left over from last year?

**Comment by Ky1e** [comment]
Bulk of the cost comes from a plastic holder for the insert. Last year we kept having problems with them tearing through. I can get s quote without them for comparison.

**Comment by mherchel** [comment]
Not sure where we ordered from in the past, but I found both http://www.usalanyards.com and http://www.lanyardsusa.com on Google. Both seem to have prices similar to years past. Hope this helps.

**Comment by Ky1e** [comment]
They've got the logo in white on the lanyard is really the only change I think. Getting a quote for just printing, no lanyards.

**Comment by carolineachee** [comment]
I have purchased the lanyards and ribbons already.

**Comment by Ky1e** [comment]
Awesome then we're moving forward with the printing.

300 tags 3 x 4 printed 2 sides on 100# gloss cover and drilled with 1 hole top center - $95.00.

The cutoff for a name on the badge is Monday the 13th.

**Comment by ultimike** [comment]
Sa-weet!!!

**Comment by carolineachee** [comment]
Here is a pic of the lanyard and holes needed... 
It would be best to have the slotted hole. I have a punch that we can make the holes with.
![img_3364 1](https://cloud.githubusercontent.com/assets/7811538/22889099/fd5a708c-f1d5-11e6-88d7-7e6dcf86549a.JPG)

Thanks,
Caroline

**Comment by ultimike** [comment]
Just a heads-up - Achieve Agency might be providing branded lanyards. If
they do, I told them they must be the clip-type (slotted) and they must get
them to us by Wednesday.

**Comment by carolineachee** [comment]
Thanks!

Caroline

**Comment by carolineachee** [comment]
Kyle,

Can you email so that I can email you the excel file. I cleaned up some of the data.. cachee@cfl.rr.com

Thanks!
Caroline
