### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#53]
We need a new owner on this

**Comment by ultimike** [comment]
I spoke with Andrew Riley - he's going to take this one over. I'm about to send an intro email for him and Rick Esser to have a smooth transition.

**Comment by ultimike** [comment]
@mherchel Please add "andrewriley" to this project and assign him to this task.

thanks,  
-mike

**Comment by andrewmriley** [comment]
Did someone say my names 3 times?

**Comment by mherchel** [comment]
![image](https://cloud.githubusercontent.com/assets/1605905/19328591/661d8efa-90a2-11e6-9f60-94ecdf03cf02.png)

**Comment by andrewmriley** [comment]
the podcast host with the most?

**Comment by ultimike** [comment]
Wow. This is awesome.

**Comment by andrewmriley** [comment]
@ultimike @mherchel Do we have a projected number of people for this year?

**Comment by mherchel** [comment]
@andrewmriley plan on 250. We can adjust the numbers a week or so out if there's any deviation.

**Comment by andrewmriley** [comment]
@mherchel Thanks. One last question. Are we looking at Saturday only for catering?

**Comment by ultimike** [comment]
Correct. Saturday only.

-mike

**Comment by ultimike** [comment]
Andrew - see https://github.com/florida-drupalcamp/fldc-issues/issues/79

Also - please assign this issue to yourself.

thanks,  
-mike

**Comment by andrewmriley** [comment]
I'll inquire about gluten-free but I realized I never posted the vegetarian options:

> As requested, we will offer a more attractive vegetarian option. We could bring your choice of one of the following: Seasoned Grilled Tofu (which people always enjoy),  Gringo Style Veggies (we use Zucchini, Yellow Squash, Onions, Tomatoes, Carrots & Broccoli), or a Homemade Black Bean Crumble (similar to a black bean burger filling but not pattied – just grilled and seasoned Tex-Mex style).

**Comment by andrewmriley** [comment]
@ultimike @mherchel When do we normally give the headcount to Gringos? We'll need that for the deposit. My contact at gringos said "a few weeks before the event" but I was wondering if we knew anything on our end.

**Comment by mherchel** [comment]
yeah, we'll have a better idea. My guess is that we'll have exactly 264.867 attendees.

**Comment by ultimike** [comment]
Andrew,

I've attached a .csv of all orders, including the "meal preference" field - that should give a good idea of vegetarian, etc...

As for a total count estimate - @mherchel has somewhat of a historical record that he can compare our current sales with. Therefore, if he says 264.867, then that's probably the best number we have.

-mike

[report-2017-01-06T0859.csv.zip](https://github.com/florida-drupalcamp/fldc-issues/files/690055/report-2017-01-06T0859.csv.zip)

**Comment by andrewmriley** [comment]
Gluten free update: Tortillas and queso sauce do contain gluten (everything else does not). Phil will bring some gluten-free corn tortillas so attendees can substitute the tortilla as needed.

**Comment by andrewmriley** [comment]
@ultimike @mherchel Do you have a current count estimate (including volunteers) that I can send to Gringos?

**Comment by mherchel** [comment]
Current estimate is 240. Right now we have 202 registered.

**Comment by mherchel** [comment]
Catering companies always prepare up to 20% more, so we could probably get away with telling them 230 or so.

**Comment by andrewmriley** [comment]
@mherchel @ultimike Any idea what time the school will open up that morning for setup?

**Comment by ultimike** [comment]
7:30am - full details:
https://github.com/florida-drupalcamp/fldc-issues/issues/86

**Comment by mherchel** [comment]
Not sure, but I remember 2 years ago they were late with the coffee. I would tell them they need to start setting up at 7:30am out front. Tell them not to be late w the ☕️ !!

**Comment by andrewmriley** [comment]
I've requested they start setting up at 7:30 :)
