### ISSUE TITLE
Order Tshirts

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#55]
dependent on #54

**Comment by ultimike** [comment]
Natalie will be handling the ordering and delivery of t-shirts.

**Comment by roberts365** [comment]
When do the T-Shirts need to be delivered?

**Comment by mherchel** [comment]
@roberts365 Let's call it one week before the camp. So February 10th.

**Comment by roberts365** [comment]
For a 50/50 cotton polyester blend Navy Blue shirts with four colors.  We are looking at a set up fee of $140.00 (4 screens at $35.00, one time fee. Any future prints with this art would be the cost of the garment and printing only.)  They are willing to take $40 dollars off to make it $100.

For 72-143 shirts: 
                    $6.90 each S-XL
                    $8.90 each 2XL
                    $9.90 each 3XL
                    $10.90 each 4XL
                    $11.90 each 5XL

For 144-299 shirts: 
                      $6.50 each S-XL
                      $8.50 each 2XL
                      $9.50 each 3XL
                      $10.50 each 4XL
                      $11.50 each 5XL

**Comment by Ky1e** [comment]
We're thinking 3 colors with the navy blue in the logo being a part of the shirt to eliminate the need for an extra color and keep costs a bit lower. Thoughts?

![screen shot 2017-01-06 at 11 17 52 am](https://cloud.githubusercontent.com/assets/9222546/21861709/f0996c68-d803-11e6-95d7-62ce16c96057.png)

**Comment by roberts365** [comment]
That would only save us $25.  If it looks better with four colors I say it is worth it.

**Comment by ultimike** [comment]
I agree with @roberts365 - go with 4 colors.

**Comment by roberts365** [comment]
I will go ahead and send the graphics to the printer and secure a slot in their schedule for us.
We should have an invoice with the total once we have all the sizes and the quantity.

**Comment by ultimike** [comment]
Sounds great - thank you Natalie!

**Comment by roberts365** [comment]
Printer secured.  Once we have the numbers, they will start printing.

**Comment by roberts365** [comment]
We are looking at 195 shirts.  Will have invoice tomorrow.
Shirts will be Gilgan 50/50 cotton/poly blend short sleeve in navy blue.

![drup](https://cloud.githubusercontent.com/assets/18563630/22525119/045dcd16-e894-11e6-8c1e-b6e3344169c6.jpeg)

**Comment by roberts365** [comment]
Shirts will be ready tomorrow for pickup.
