### ISSUE TITLE
Bags

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#56]

**Comment by ultimike** [comment]
I'll do a count of what we have left-over from previous years, and order new bags based on that number.

**Comment by ultimike** [comment]
We have 47 grey bags from last year.

I'm thinking that we should order 200 of these: https://www.holdenbags.com/products/little-tex-grocery-bag

To mix things up a bit, how about we get yellow bags with blue print (the Florida Drupal Diver with no text - same as last year)?

-mike

**Comment by ultimike** [comment]
Using the artwork from https://github.com/florida-drupalcamp/fldc-issues/issues/54#issuecomment-276111126, I've ordered 200 royal blue bags with light blue printing.
