### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#58]
Let's get some sponsors. I know Lullabot committed to a bronze. I'll throw them up on the site. Note all previous sponsors are just unpublished - so you can just adjust their sponsorship level and publish them when necessary.

**Comment by ultimike** [comment]
Ok - the first round of sponsorship emails just went out.

@mherchel In the next newsletter, will you put out a call for sponsors?

thanks,  
-mike

**Comment by mherchel** [comment]
@ultimike How we looking sponsorship-wise?

**Comment by ultimike** [comment]
We currently have $7,750 in committed sponsorships, I'll be making another push after the new year.

For the budget, with our estimates for attendance, if we don't get any additional sponsors, we'll have a shortfall of about $2k, which will be (easily) covered by our nest egg.

**Comment by Ky1e** [comment]
GoDaddy just got back to me and said it's too short of a notice but they'll be happy to sponsor next year. FYI.

**Comment by ultimike** [comment]
Kyle - shoot me an email with the contact info?

thanks,
-mike

**Comment by Ky1e** [comment]
Done

**Comment by mherchel** [comment]
Closing.
