### ISSUE TITLE
Food on Friday

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#59]
We'll need to feed the beginner's track on Friday. This will eat into our budget. FYI

@ultimike

**Comment by ultimike** [comment]
Yeah, we'll have to see how the budget goes. I told Steve Burge to count on a 1.5 hour lunch on Friday in case we need to call it a "lunch on your own" thing.

-mike

**Comment by mherchel** [comment]
At GNV Barcamp we ended up buying lunch from publix. We got platters of sandwiches and it turned out really well for a small amount of money. I'm guessing something like that would cost $200 for 40 people. It's a cheap option if we can afford it.

**Comment by ultimike** [comment]
Yep - makes sense.

-mike

**Comment by ultimike** [comment]
Let's keep this in the "play it by ear" category. If we can find someone to help out with it, then we can spend the $$$ to make it happen. I can't do it because I'll be teaching...

-mike

**Comment by mherchel** [comment]
@ultimike So food? Also Coffee?

**Comment by ultimike** [comment]
Boxed lunches from TooJays:

- 55 "no preference"  
- 10 vegetarian
- 5 vegan
- 70 total boxed lunches (labelled, napkins, mayo/mustard, etc...)
- $10.79/each
- They'll bring ice tea and lemonade to drink for $6.79/gallon (6 gallons) - includes cups and everything.  
-  They'll bring a cooler of ice as well.  
- I can call them next week with final numbers.
- Will deliver between 11:30-noon. 
- I spoke with Sarah on 2/10/17 via (561) 472-0567.
- Total cost: $830.93 (I paid with my business Visa)

**Comment by ultimike** [comment]
- Updated to 85
- 10 vegetarian
- 4 vegan
- 71 mixed
- 7 gallons of drink
- Total cost: $1,011.30
