### ISSUE TITLE
Session Recordings

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#61]
Looking into http://bluedropshop.com/blog/drupal-camp-session-recordings-year-review

**Comment by Ky1e** [comment]
My only constraint is that I need to be back in Chicago in time for work on Monday, so I'll be constrained to return flights late afternoon Sunday or red-eye Monday morning. There seem to be enough options at the moment for a Sunday return, but in either case airfare is currently $400-500. Hopper predicts that will drop, but I've had mixed results with how much it thinks it will drop. So assuming I can get a Sunday return flight, two nights at the camp hotel, and cab fare to and from the airport, total cost would be around $800. And it would increase if I can't get a suitable flight home on Sunday.

Is that something that can fit in the camp budget?

**Comment by ultimike** [comment]
I spoke with Kevin at BADCamp. I told him that we want to make it happen,
but I couldn't give him a definite answer until we see how our sponsorships
shape up.

Based on his email (above) and my conversations with him, this is what I
think it will take to make it happen:

1.  Somewhere around $1k to cover his travel expenses.
2.  Someone to take him to/from the airport as well as to/from the hotel to
the venue.
3.  Room monitors for each room to ensure "the button is pressed".
4.  Power strips at each podium.
5.  Prior to the event, it would be helpful to send him model numbers (and
ports) for each of the projectors.

-mike

**Comment by Ky1e** [comment]
How we looking @ultimike?

**Comment by ultimike** [comment]
Not bad. You?

Heh.

I haven't had too much time to do anything other than followup with some
sponsors and potential trainers. I'll have some time over the holidays to
get my tasks moving again...

thanks,
-mike

**Comment by Ky1e** [comment]
I'd say roughly 6/10. Not a grenade but still a respectable number. Let me know if you need assistance with anything.

**Comment by ultimike** [comment]
@Ky1e Let's proceed with the session videos. Will you contact Kevin to get the ball rolling?

thanks,  
-mike

**Comment by Ky1e** [comment]
@ultimike Will do.

**Comment by Ky1e** [comment]
Sounds good Kyle. I'm still in. I'll book hotel and airline soon. If you are using the D/A, what is your camp code for reimbursements? -Kevin

@ultimike

**Comment by ultimike** [comment]
Kevin,

We're not using the DA for $$$. Just shoot me an email with receipts and
we'll get you reimbursed pretty quickly.

Looking forward to it!

thanks,
-mike

**Comment by Ky1e** [comment]
Traveler 1: Adult $403.40
Flight: $348.83
Taxes and Fees: $54.57
Flight Total: $403.40

Summary of cost. Got the email, I'll forward when I get to the office.

**Comment by ultimike** [comment]
Ask him to keep his receipts - we'll reimburse.

thanks,
-mike

**Comment by Ky1e** [comment]
List from Kevin

Venue / Setup
. Who is my primary on-site contact from camp?
. Who is/are my primary on-site contact(s) from the venue (room access, room setup, equipment issues, etc.)?
. How many session rooms will the camp have?
. Can I get access to any rooms the day before sessions? If so, what time?
. What is the earliest I can get access to rooms during camp?
. I need a full power strip at each podium (depending on the orientation of the plugs, the kit can block off a full strip)

Recording / Camp
. Do you want opening/closing remarks recorded?
. Will I have access to on-site venue storage for A/V bag?
. I need room monitors to help ensure speakers remember to start/stop the recording
. I need YouTube credentials
. If I can get access to ethernet for upload, that's a bonus
