### ISSUE TITLE
Potential Training - Docker

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#65]
at Drupalcon Chattanooga, Lisa Ridley said she might be interested in doing an "Intro to Docker" training at FLDC. 

@ultimike Are you officially coordinating the training? Do you want to handle this?

https://www.drupal.org/u/lhridley
https://twitter.com/lhridley

**Comment by JCL324** [comment]
Yes please! Love to attend this training.

**Comment by ultimike** [comment]
I've sent Lisa an email via her drupal.org contact form.

thanks,  
-mike

**Comment by ultimike** [comment]
I heard back from Lisa - she's working on getting it approved by her boss. I'll check in with her next week if I don't hear back.

**Comment by ultimike** [comment]
Closing in lieu of https://github.com/florida-drupalcamp/fldc-issues/issues/60
