### ISSUE TITLE
Volunteers get a free (comp'd) ticket

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#69]
Are you helping out with FLDC2017? If so, you get a free ticket to the event!

If you haven't already registered, just ask @mherchel or @ultimike for the coupon code. If you have already registered, we can't (won't) refund your money, but you're eligible for a great big hug from @mherchel.

thanks,  
-mike

**Comment by Ky1e** [comment]
If we got individual sponsorships can we get a great big hug from @ultimike?

**Comment by ultimike** [comment]
Maybe for two individual sponsorships...

**Comment by Ky1e** [comment]
Deal
![image](https://cloud.githubusercontent.com/assets/9222546/21572499/83b9edee-cea7-11e6-92d1-7819d58a739d.png)
