### ISSUE TITLE
Indoor signage

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#71]
@mherchel has the master plan for this in his head. Steven Williams will assist.

thanks,  
-mike

**Comment by StevenGFX** [comment]
Will be glad to help! :sunglasses:

**Comment by ultimike** [comment]
I have some notes from some Drupal event presentation/BoF I was at - one note I had is that "good signage helps people feel comfortable". I think it was specifically referring to clear venue maps to help people feel oriented. 

Just something to consider.

thanks,  
-mike

**Comment by mherchel** [comment]
@StevenGFX Any update on the design for http://www.stickersbanners.net/x-banners.html?

**Comment by StevenGFX** [comment]
@mherchel Just saw this. I do have a sign. Would like you to look at it so i can finish it up. Content was really all that I had a question with. I can't make the call today but maybe I can get with you sometime this evening!

**Comment by StevenGFX** [comment]
Here's my draft. Wasn't sure what should be included on it but we can start here. I think a few elements probably need to be tweaked a bit. I tried to make it generic so it can be used with future conferences. I used last years Drupal Diver logo but adjusted the colors to the older Drupal Diver.
 
[fldc-signage-roll-up_draft-1.pdf](https://github.com/florida-drupalcamp/fldc-issues/files/725088/fldc-signage-roll-up_draft-1.pdf)

**Comment by mherchel** [comment]
@StevenGFX Looks good! We do need a bunch of changes though. If you want to hop on a hangout or call, to go over it all, let me know. Here are changes:

* We need the new logo to match the site/social, etc
* No need for description or QR code. People will only see this sign when they're at the event.

Let me know when you have time, and we can talk about it. Thanks again,

**Comment by StevenGFX** [comment]
[fldc-signage-roll-up.pdf](https://github.com/florida-drupalcamp/fldc-issues/files/738213/fldc-signage-roll-up.pdf)

**Comment by ultimike** [comment]
Cool. Is this going to be a big sign that folks can stand in front of to
take selfies with?

**Comment by mherchel** [comment]
We're getting two of these:

![image](https://cloud.githubusercontent.com/assets/1605905/22831871/f1291e34-ef79-11e6-8959-7cd61028e667.png)

I just ordered. The total came to $179.97.

They look like this. Note to @StevenGFX I had to adjust the size (was 71" tall not 78") and remove the bleed. But it's looking good!


![screen shot 2017-02-10 at 10 17 25 am](https://cloud.githubusercontent.com/assets/1605905/22831964/42c1da42-ef7a-11e6-9fb5-4b3f3eb5ae3c.png)

**Comment by ultimike** [comment]
OUTSTANDING!

(get it? outSTANDing? Because it's a stand-up thing...)

**Comment by ultimike** [comment]
Does that place that you're ordering those from sell tablecloths that we
could put branding on for our registration tables? If so, let's get 4 or so
of them as well (if you guys have the time to make that happen - if not, no
worries - I saw some at the New Jersey camp and they looked very
professional).

**Comment by mherchel** [comment]
@ultimike possibly. I have time after lunch to check, but now I gotta get some shit dun.

http://www.stickersbanners.net

**Comment by ultimike** [comment]
They don't do tableclothes. No worries.

**Comment by mherchel** [comment]
anything else to get?

**Comment by ultimike** [comment]
Nothing I can think of at the moment - and the last thing I want to do is
hold the process up.

**Comment by mherchel** [comment]
Cool. I just approved the proof. Should ship today w 3 business day turnaround. So, I should receive on Wednesday or Thurs at the latest.

**Comment by mherchel** [comment]
thinking about it. I'm going to get it shipped faster. Just in case.

**Comment by ultimike** [comment]
https://m.popkey.co/ca8f87/AoYjv_f-maxage-0.gif

**Comment by mherchel** [comment]
dun

**Comment by mherchel** [comment]
tracking https://track.aftership.com/fedex/785571448916
