### ISSUE TITLE
Major Issue Triage Sprint?

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#72]
xjm suggested that we do a major issue triage sprint at FLDC (see http://xjmdrupal.org/blog/drupal-8-major-triage-new-orleans and https://www.drupal.org/node/2474049).

We're thinking we could do this on Sunday.

In order to make this happen, we need some sprint leads. Perhaps:

Ted Bowman
Adam Bergstein (confirmed)  
Marc Drummond
Matthew Connerton
Others?

-mike

**Comment by mherchel** [comment]
Marc Drummond cannot do it (he's leaving Sunday morning).

**Comment by ultimike** [comment]
xjm emailed me about this over the weekend:

> Any further thoughts on this? I'd be glad to do a hangout or such with camp organizers if it's helpful, to answer any questions etc. I am traveling Jan. 19-27 but we could schedule a time after that.

I'm pretty sure Ted Bowman isn't making down to the camp, so he's out.

-mike

**Comment by ultimike** [comment]
Ted will lead this if we pay for his plane ticket. We have the $$$ - thoughts?

thanks,  
-mike

**Comment by mherchel** [comment]
I'm down for that. Adam is doing it too. Tell Ted we will trade him a plane ticket for a beer.
