### ISSUE TITLE
Getting the word out

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#73]
As awesome and Mike Herchel thinks he is, we need some additional help getting the word out about Florida DrupalCamp 2017 - especially to non-Drupal web development user groups.

Who can help?

thanks,  
-mike

**Comment by Ky1e** [comment]
There is a ton of local dev groups with 20-50 members each on meetup.com. I attend 4 or 5 that meet regularly that I can mention the camp in. Not sure what effect that'll have. I do a LOT of volunteer work for http://www.doporlando.com/ which is a networking organization on steroids. I can make an intro if we're looking for more sponsors. Most of this is all local to Orlando though. :)

**Comment by ultimike** [comment]
Kyle,

Any/all of that would be great.

We're always looking for more sponsors, so if you want to make an intro,
I'm all ears. Whomever you approach or tell about the camp, please document
in this issue so we have as little overlap as possible.

thanks,
-mike

**Comment by iribarne** [comment]
Mike and Kyle,

I began spreading the word in South Florida. I created an event on meetup (https://www.meetup.com/South-Florida-Drupal/events/236586652/) and on Facebook as well (https://www.facebook.com/events/719074344924494/). I also contacted Adam Culp, organizer of South Florida PHP and Sunshine PHP Conference, and he told me that he would help spread the word. Boca JS meets up in two days (https://www.meetup.com/Boca-JS/events/236284361/), so I will spread the word there as well.

I will continue to promote Florida DrupalCamp in South Florida. See you guys next month!

Happy New Year,
Hector

**Comment by ultimike** [comment]
I've submitted the event to http://orlandotech.org/events/ and http://techevents.us/orlando/

**Comment by alexdmccabe** [comment]
I submitted the event to https://opensource.com/resources/conferences-and-events-monthly?month=2017-02. It needs approval, so it hasn't shown up yet.

I also listed it on the Orlando Drupal group on meetup.com: https://www.meetup.com/Orlando-Drupal/events/236681208/

**Comment by ultimike** [comment]
Here's a Google Doc with some text for marketing the camp: https://docs.google.com/document/d/1T1Ww5DYPJAtU7Os0aOMFJ9oAOVlRAeW5iqGIBEF-qQU/edit
