### ISSUE TITLE
Sponsor Happiness - day(s) of event

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#74]
During the event, we're going to need a couple of volunteers to visit each of the sponsors at their tables (or where ever they might be) to ensure they have everything they need and (more importantly) let them know how much we appreciated their involvement.

Things we can offer include:

1.  Make introductions with attendees.  
2.  Escort sponsors to the front of the lunch line (this is a new, unadvertised perk we're giving sponsors).  
3.  Other ideas?  

I'll be involved in this, but I'll need some help.  

-mike

**Comment by mherchel** [comment]
@willjackson is looking to help out.

**Comment by willjackson** [comment]
@ultimike - We are driving down from Aiken, SC and will likely be in late Friday and will be driving back early Sunday.  I am presenting a session in the first time slot for Saturday morning, but outside of that I am available to help where needed.

**Comment by ultimike** [comment]
Sponsors needing tables:

Seeva, DrupalEasy, Last Call, Digital Echidna, Achieve Agency, Spinspire
