### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#75]
We love Caroline and Karan. Do what they say.

I'd like for us to have two different color lanyards this year - one for folks who don't mind being in pictures, one for folks that don't want to be in pictures. We probably only need 10-20 of the latter, so let's make that happen.  

-mike

**Comment by carolineachee** [comment]
Thanks @ultimike !

**Comment by carolineachee** [comment]
Mike,

Can you get me a list of the people associated with the corporate sponsors? I am working on setting the ribbons... @ultimike 

Thanks,
Caroline

**Comment by carolineachee** [comment]
Mike and Mike,

The t-shirt size did not get pull from the registration record... So we have no size data. Can someone do a one shot and get the info from the Eventbright data??

Thanks,
Caroline

**Comment by ultimike** [comment]
Caroline - I've attached a .csv export of attendees with names, emails, job titles, and discounts. The "discounts" column shows the coupon code that was used - if any. That can be used to match up an attendee with a sponsor. 

There may be attendees associated with sponsors that didn't use a coupon code - in that case, your guess is as good as mine. 

I'm happy to regenerate this report at any time. 

thanks,  
-mike
[report-2017-01-05T1046.csv.zip](https://github.com/florida-drupalcamp/fldc-issues/files/687636/report-2017-01-05T1046.csv.zip)

Note to self: EventBrite | Analyze | Event Reports | Attendee Summary

**Comment by ultimike** [comment]
Caroline - and here is a .csv with the t-shirt sizes...

thanks,  
-mike

[report-2017-01-05T1050.csv.zip](https://github.com/florida-drupalcamp/fldc-issues/files/687645/report-2017-01-05T1050.csv.zip)

**Comment by carolineachee** [comment]
Mike! 

Thanks
Caroline

**Comment by carolineachee** [comment]
Mike and Mike,

We need to get Feature Speaker - MEGAN SANICKI - to register so that she will have a name tag! The next thing I will be doing is checking on the other speakers....

Thanks,
Caroline

**Comment by carolineachee** [comment]
Mike,

Can you please send me a copy of the file at around 3:30 today.

Thanks,
Caroline

**Comment by carolineachee** [comment]
Thanks!
