### ISSUE TITLE
AV Wrangler

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#76]
For the past few years, the totally awesome Linda Cook has been handling this - hopefully, she'll do it again...

I did a count of what we have on-hand:

- 4 HDMI cables
- 1 DVI cable

![image](https://cloud.githubusercontent.com/assets/1727889/21578061/4bc09a5c-cf40-11e6-9fae-56393d399f3b.jpeg)

**Comment by lscook** [comment]
Lol. Ok, sign me up.

**Comment by mherchel** [comment]
Closing. Thanks @lscook!
