### ISSUE TITLE
Genius Bar

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#77]
@mherchel had the idea for a "Genius bar". An area - possibly in the sponsor hall to help drive traffic - where folks can go to ask questions about their Drupal project. 

To make this happen, we'll need someone to volunteer to be in charge of this. This person would be responsible for scheduling other volunteers at the table (maybe 2 per shift) and getting things setup and torn down each day.

Volunteer below!

-mike

**Comment by mherchel** [comment]
Yeah, this idea is taken from WordCamps, where it's a thing.

**Comment by Ky1e** [comment]
I participated in the one at WordCamp Orlando. It was a lot of fun and you meet a lot of cool people. It was broken up into three sections so we had one corner for design, site building, and plugin development.  Easier for people to pop in and out.

**Comment by mherchel** [comment]
Where should this be located? Library?

**Comment by Ky1e** [comment]
I'll man this and help direct traffic in between session recordings.
