### ISSUE TITLE
Social Media Wrangler

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#78]
The social media wrangler will post various information on our social media account in the time leading up to the camp. In addition, after the camp, we'll need to send out posts thanking attendees, speaker, trainers, and sponsors.

Ideally, we’d like 1-2 posts per day on each of the following:

https://twitter.com/fldrupalcamp
https://www.facebook.com/groups/43405081389/
https://www.linkedin.com/groups/105073

We’ll need sponsor tweets (weighted by sponsorship level) - see https://docs.google.com/spreadsheets/d/1q4wbQKCXBwFCyr28xHj0OHzElHl1ERbG4hnhR1Cr68U/edit as well as general tweets promoting the camp. 

We could have multiple people on this task.

**Comment by gscampbell64** [comment]
I am happy to continue to be town crier for this year.  I do suggest it be more than one person so the posts have a little variety.  Also, is #fldc17 the hashtag for this year?

**Comment by ultimike** [comment]
@gscampbell64 Do you have everything you need to get going on this? If you could take care of the daily sponsor tweets, that would be great.

I've created a new "2017 Sponsor Tweets" tab on this spreadsheet with some additional information for you: https://docs.google.com/spreadsheets/d/1q4wbQKCXBwFCyr28xHj0OHzElHl1ERbG4hnhR1Cr68U/edit#gid=1896545185

The schedule and content of each tweet is up to you. The main goal is to thank and promote each sponsor the required number of times. We don't have to get all of these done prior to the camp, we can save some for after the event as well.

Make sense?

thanks,  
-mike

**Comment by Ky1e** [comment]
There's a few tweet schedulers out there you can use so you can space them out without having to remember to post each one. 

https://www.cnet.com/pictures/6-ways-to-schedule-your-tweets/

**Comment by ultimike** [comment]
I went ahead and scheduled all the sponsor tweets, so we're good-to-go with that.

**Comment by mherchel** [comment]
Closing. I don't see anyone else jumping in this late.
