### ISSUE TITLE
Session Scheduling Requests

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#80]
This issue is to log all requests that come from speakers on which day they want to speak.

**Comment by mherchel** [comment]
Kelly from Last Call Media wants all his sessions on Saturday
Cottser from Digital Echinada also wants both is sessions on Sat

**Comment by Ky1e** [comment]
David from Orange Blossom Media would like his on Saturday afternoon. He's doing a dev workshop Saturday morning.

**Comment by mherchel** [comment]
Good Day, 

I would need to present my accepted session "DRUPAL 8 CACHING: A DEVELOPER’S GUIDE" https://www.fldrupal.camp/sessions/approved/florida-drupalcamp-2017/development-performance/drupal-8-caching-developer%E2%80%99s-guide on Sunday. If I could do 10AM on Sunday that would be great. Can that work? 

Thanks,

Peter Sawczynec

**Comment by mherchel** [comment]
Dear Organizing Team, 

Thank you for selecting my session. Given a preference, I would like to deliver my session on Saturday. May have to fly out on Sunday.

Happy to be present and be part of Florida DrupalCamp.😀

Best,
Shailesh Gogate

**Comment by mherchel** [comment]
I wanted to let you know that I will not be able to attend Sunday. I am attending on Saturday. So I request that my session be scheduled for Saturday. Link to session - https://www.fldrupal.camp/sessions/approved/florida-drupalcamp-2017/site-building/selling-healthcare-insurance-plans-drupal

Thank you. --Jitesh
