### ISSUE TITLE
Session Acceptance - Needed item to email

### ISSUE THREAD

**Issue by carolineachee** [florida-drupalcamp/fldc-issues#82]
Please when issuing an acceptance of a session please ask them to register for camp if they are not already registered.

Just a heads up 13 out of the 24 speakers are not yet registered. I know some may not have registered because they are waiting to find out if their topic has been excepted.

The following speakers have not yet registered.... 
Tyler	Ashbaugh
ADAM	BERGSTEIN
ERICH	BEYRENT
KIRSTEN	BURGARD
Jorge	Diaz
SHAILESH	GOGATE
DAN	GURIN
DAN	HANSEN
DAVID	LAIETTA
DWAYNE	MCDANIEL
Ozzie	Osband
ERIC	SEMBRAT
RYAN	WAGNER
 
 
Thanks,
Caroline

**Comment by mherchel** [comment]
@carolineachee Sessions have been accepted (and some rejected). Can you check once again, and we'll shoot an email? The current list is at https://www.fldrupal.camp/admin/sessions
