### ISSUE TITLE
Archive 2012, 2013, and 2014 sites to static html. 

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#83]
2013.fldrupalcamp.org is running Drupal 7.20, which is vulnerable to the Drupalgeddon bug and many others. Looking at the users table, it's been hacked. There are new users despite not having user registration activated: 

![image](https://cloud.githubusercontent.com/assets/1605905/22132781/27b36398-de8a-11e6-81b9-ff09295b46b6.png)

All of our registered users registered through the site, which means that it's likely that they have our whole users table along with everything else. 

Anyway, this needs to be archived to static html like the others. I'm not sure if we should go about notifying the affected people. 

cc @JCL324 @ultimike

**Comment by mherchel** [comment]
Same for http://2012.fldrupalcamp.org, which is running 6.20. It's user table is filled with spammers.

**Comment by mherchel** [comment]
2014 also needs to be archived. It's on 7.24. Doesn't appear to be overtly hacked like the others.

**Comment by andrewmriley** [comment]
I'll see if I can grab html copies.

**Comment by JCL324** [comment]
I have disabled 2012, 2013, 2014 from Apache on my Linode. I have 2014 archive kicking around somewhere, the archive was prepared for on the server.

@andrewmriley, I have a process that works well (did 2016, 2015) using httrack, so much better than wget.

**Comment by andrewmriley** [comment]
@JCL324 Sounds good!

**Comment by JCL324** [comment]
2014 is backup and archived.  @andrewmriley, do you know a away to prevent access to /users from showing the folders without preventing access to users/jcl324? I have a redirect in .htaccess to prevent /user and /node.

**Comment by mherchel** [comment]
@andrewmriley ☝️ Lets get this taken care of :)

**Comment by JCL324** [comment]
2012 and 2013 are now live and archived.  I've tried my best to prevent registration, or other admin type links.

**Comment by mherchel** [comment]
Thank you @JCL324!

**Comment by JCL324** [comment]
Let's not close yet in case @andrewmriley can help with the .htaccess rules.
