### ISSUE TITLE
Venue notes

### ISSUE THREAD

**Issue by ultimike** [florida-drupalcamp/fldc-issues#86]
I'm working on finalizing the details of the venue.

Here are the hours we agreed upon to have the building available to us:

- Friday 8am-5pm
- Saturday 7:30am-6:30pm
- Sunday 8am-5pm

As in previous years, we will pay for security and custodial services. FTC will provide a key holder for us to assist us.

Our original contact (Anissa Mills) is no longer with FTC. I'm currently working with Dr. Karen White-Goyzueta (Vice President, Career Services), but will also be working with Dean Karen Oporto and Prof. Rigoberto Maximo on helping to coordinate everything. 

Dr. White-Goyzeuta indicated that they're going ahead with the event because of our previous commitment with Anissa and that future events are not guaranteed...

-mike

**Comment by mherchel** [comment]
![image](https://cloud.githubusercontent.com/assets/1605905/22309733/7b72c728-e31a-11e6-9a10-a809566bf802.png)

**Comment by ultimike** [comment]
Raul - custodial services.

- $15/hour?
- Saturday from noon - 7pm?
- Sunday from noon - 6pm?

He will get back to me with details.

**Comment by ultimike** [comment]
Custodial is all set. The vendor is "CC Cleaning services" and the amount is $273.92. Don is sending me a check that I can hand them at the event.

**Comment by ultimike** [comment]
Security is via Amir Ghaffari (407-271-5747). I spoke with him on 2/6/17 and he told me his colleague Frank would be calling me to finalize the arrangements.

**Comment by ultimike** [comment]
I spoke with Frank Tejera from Securitas - here's the deal for FLDC17 security

- Friday - FTC security already present
- Saturday - 7:30am-6:30pm
- Sunday - 8am-5pm

Frank will send me a proposal.
