### ISSUE TITLE
Request for free tickets

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#88]
This came in on the facebook page:

![image](https://cloud.githubusercontent.com/assets/1605905/22862601/57f0c0b8-f100-11e6-9b8f-2670b4f4fa7a.png)

@ultimike Thoughts?

**Comment by mherchel** [comment]
Friends on FB with Ryan. Maybe we should ask him?

**Comment by ultimike** [comment]
I'll forward to Ryan and ask him what he thinks.

-mike

**Comment by ultimike** [comment]
The gentlemen in Portland had a good idea for this - can we ask them to volunteer during the camp in exchange for their tickets? Where do we need help? Setup and cleanup?
