### ISSUE TITLE
For inclusion to Ultimike's slide deck

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-issues#90]
@ultimike 

In addition to the usual stuff...

* Cancellation of Ryan Wagner's session on "Making PHPStorm work for you". This is off the website, but will be on the large printed schedule
* Genius bar - speakers will be hanging out there after their sessions
* After Party - Sponsored by Code Journeymen & Kanopi
* Code Sprints

**Comment by mherchel** [comment]
* 30 min between sessions

**Comment by ultimike** [comment]
Speakers - after your session, head to the "Genius bar" for questions.

**Comment by ultimike** [comment]
All added.
