### ISSUE TITLE
Figure out Lodging / hotel packages

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#92]
Same hotel as last year?

**Comment by JCL324** [comment]
NO!! Comfort Suites is over. We want the one right behind Bubbalous, where @C13L0 stayed and was very impressed. And I think she paid a bit less _without_ the discount.

**Comment by C13L0** [comment]
@JCL324  is correct! I stayed at the Hilton Garden Inn next to Bubbalous. My bed was comfortable (gasp), the room was quiet (gasp), there was a nice bar in the evenings, and breakfast was excellent. 

I paid a total of 318.49$ for three days.

Hilton Garden Inn Orlando East/UCF Area
1959 N. Alafaya Trail, Orlando, FL 32826
T:  1 407-992-5000

**Comment by C13L0** [comment]
OH, the only thing I can recommend is to bring plenty of chargers. Unlike most hotels that have charging ports...they had none. /sighs

**Comment by Ky1e** [comment]
Fancy shmancy. I'll give them a ring and see what's what. Do we have a count for the room block from last year @ultimike ?

**Comment by ultimike** [comment]
I do not, but I believe that @mherchel will.

**Comment by mherchel** [comment]
probably 40 room nights. I need to reach out to hotels to make sure we get a couple free nights for our featured speakers.

**Comment by mherchel** [comment]
@JCL324 @C13L0  I contacted the Hilton Gardens (behind Bubbalous) they don't have room for a room block. But they do have some rooms avail if you want to reserve now. I've contacted Comfort Suites again. 

What's the gripe so I can bring it up to the person?

**Comment by JCL324** [comment]
It's noisy if you get a room on Alafaya, and no black out curtains for the street lights. @C13L0 thought the beds were terribly uncomfortable.
