### ISSUE TITLE
Figure out featured speakers

### ISSUE THREAD

**Issue by Ky1e** [florida-drupalcamp/fldc-issues#94]

**Comment by ultimike** [comment]
I think this is one of our top priorities (along with the web site and sponsorships).

Some ideas

*  Angie - https://events.drupal.org/dublin2016/sessions/how-our-competitors-are-kicking-drupals-ass-and-what-we-can-do-about-it  
*  Security speaker  
*  Decoupled speaker

**Comment by Ky1e** [comment]
Sally, and Adam are locked in.
